"""SQL safety guardrails for the analytics agent.

These functions enforce a read-only contract before any SQL generated by the
model is executed. They are deliberately conservative: anything that is not a
plain ``SELECT`` / ``WITH`` read query is rejected.
"""

from __future__ import annotations

import re

# Statements that mutate data or schema. Any of these => unsafe.
WRITE_KEYWORDS = [
    "INSERT",
    "UPDATE",
    "DELETE",
    "DROP",
    "ALTER",
    "TRUNCATE",
    "MERGE",
    "CREATE",
    "GRANT",
    "REVOKE",
    "REPLACE",
    "ATTACH",
    "COPY",
    "CALL",
    "EXECUTE",
    "PRAGMA",
]

# Read-only statements are allowed to start with these tokens.
_ALLOWED_START = ("SELECT", "WITH", "SHOW", "DESCRIBE", "DESC", "EXPLAIN")

_COMMENT_RE = re.compile(r"(--[^\n]*)|(/\*.*?\*/)", re.DOTALL)
_IDENT_RE = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\b")


def strip_sql_comments(sql: str) -> str:
    """Remove ``--`` line comments and ``/* */`` block comments."""
    return _COMMENT_RE.sub(" ", sql)


def _tokens(sql: str) -> list[str]:
    return _IDENT_RE.findall(sql.upper())


def is_read_only_sql(sql: str) -> bool:
    """Return True only if ``sql`` is a single read-only statement.

    Blocks INSERT/UPDATE/DELETE/DROP/ALTER/TRUNCATE/MERGE/CREATE/GRANT and
    friends, multiple statements, and anything not starting with an allowed
    read keyword.
    """
    if not sql or not sql.strip():
        return False

    clean = strip_sql_comments(sql).strip().rstrip(";").strip()
    if not clean:
        return False

    # Reject multiple statements (a stacked write after a select).
    if ";" in clean:
        return False

    upper = clean.upper()
    first = upper.split(None, 1)[0] if upper.split() else ""
    if first not in _ALLOWED_START:
        return False

    tokens = set(_tokens(clean))
    if tokens & set(WRITE_KEYWORDS):
        return False

    return True


def find_write_operations(sql: str) -> list[str]:
    """Return the list of write keywords found in ``sql`` (empty if safe)."""
    clean = strip_sql_comments(sql)
    tokens = set(_tokens(clean))
    return sorted(tokens & set(WRITE_KEYWORDS))


def validate_tables(sql: str, allowed: set[str] | list[str]) -> tuple[bool, list[str]]:
    """Check that every table-like token referenced is in ``allowed``.

    Returns ``(ok, unknown_tables)``. Uses FROM/JOIN detection so that column
    names and functions are not mistaken for tables.
    """
    allowed_upper = {a.upper() for a in allowed}
    clean = strip_sql_comments(sql)
    refs = re.findall(r"\b(?:FROM|JOIN)\s+([A-Za-z_][A-Za-z0-9_\.]*)", clean, flags=re.IGNORECASE)
    unknown: list[str] = []
    for r in refs:
        table = r.split(".")[-1].upper()
        if table not in allowed_upper:
            unknown.append(table)
    return (len(unknown) == 0, sorted(set(unknown)))


def enforce_limit(sql: str, default_limit: int = 1000) -> str:
    """Append ``LIMIT`` to a non-aggregate SELECT that lacks one.

    Aggregate queries (containing GROUP BY or an aggregate function without
    per-row output) are left untouched. This is a best-effort helper.
    """
    clean = strip_sql_comments(sql).strip().rstrip(";").strip()
    upper = clean.upper()

    if "LIMIT" in upper:
        return clean

    has_group = "GROUP BY" in upper
    has_agg = bool(re.search(r"\b(SUM|COUNT|AVG|MIN|MAX)\s*\(", upper))
    # Aggregates that collapse to a single/grouped result don't need a row cap.
    if has_group or (has_agg and "GROUP BY" not in upper and "FROM" in upper and not _has_star(upper)):
        return clean

    return f"{clean} LIMIT {default_limit}"


def _has_star(upper_sql: str) -> bool:
    m = re.search(r"SELECT\s+(.*?)\s+FROM", upper_sql, flags=re.DOTALL)
    return bool(m and "*" in m.group(1))


def safety_check(sql: str, allowed_tables: set[str] | list[str] | None = None) -> dict:
    """Full guardrail report for a SQL string.

    Returns a dict with ``read_only``, ``write_ops``, ``unknown_tables`` and a
    boolean ``safe`` combining the checks.
    """
    read_only = is_read_only_sql(sql)
    write_ops = find_write_operations(sql)
    unknown_tables: list[str] = []
    if allowed_tables is not None:
        _, unknown_tables = validate_tables(sql, allowed_tables)
    return {
        "read_only": read_only,
        "write_ops": write_ops,
        "unknown_tables": unknown_tables,
        "safe": read_only and not write_ops and not unknown_tables,
    }
